---
- name: create self signed cert
  command: >
    openssl req -x509 -nodes -subj '/CN={{ ansible_host }}' -days 365 -newkey rsa:4096 -sha256 -keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt
    creates=/etc/ssl/certs/server.crt
