---
- name: metro-nginx - create nginx metro site config
  template:
    src: metro-site-config.j2
    dest: /etc/nginx/sites-available/metro-site-config
    owner: root
    group: root
    mode: 0644

- name: metro-nginx - enable nginx metro site config
  file:
    src: /etc/nginx/sites-available/metro-site-config
    dest: /etc/nginx/sites-enabled/metro-site-config
    state: link
