---
- name: create nginx metro site config
  copy:
    src: metro-site-config
    dest: /etc/nginx/sites-available/metro-site-config
    owner: root
    group: root
    mode: 0644

- name: enable nginx metro site config
  file:
    src: /etc/nginx/sites-available/metro-site-config
    dest: /etc/nginx/sites-enabled/metro-site-config
    state: link
