---
- name: metro-nginx - ensure  directory
  file:
    path: /home/mirror/funtoo
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: metro-nginx - create metro index site
  copy:
    src: index.html
    dest: /home/mirror/funtoo/index.html
    owner: root
    group: root
    mode: 0644
