---
- name: metro nginx - install needed software
  include_tasks: 01_software.yml

- name: metro nginx - create self signed certificate
  include_tasks: 02_certificate.yml

- name: metro nginx - ensure site config exists and enabled
  include_tasks: 03_config.yml

- name: metro nginx - ensure index.html exists
  include_tasks: 04_index.yml

- name: metro nginx - ensure nginx startet
  include_tasks: 05_start.yml