---
- name: lxd - ensure app-emulation/lxd is installed
  portage:
    package: app-emulation/lxd
    state: present
  register: out
- debug: var=out.stdout_lines

- name: lxd - ensure dev-python/python3-lxc is installed
  portage:
    package: dev-python/python3-lxc
    state: present
  register: out
- debug: var=out.stdout_lines
