---
- name: lxd - ensure lxd is started und enabled
  service:
    name: lxd
    state: started
    enabled: yes
  register: out
- debug: var=out.stdout_lines

- name: lxd - pause for 5 seconds
  pause:
    seconds: 5
  register: out
- debug: var=out.stdout_lines