---
- name: lxd - ensure lxd is started und enabled
  service:
    name: lxd
    state: started
    enabled: yes
  register: out
- debug: var=out.stdout_lines

- name: lxd - pause for 10 seconds
  pause:
    seconds: 10
  register: out
- debug: var=out.stdout_lines