---
- name: download lxd image
  get_url:
    url: "{{ lxd_image_url }}"
    dest: /tmp/lxd.img
    mode: 0644
  register: out
- debug: var=out.stdout_lines

- name: import lxd image
  shell: /usr/bin/lxc image import /tmp/lxd.img --alias {{ image_alias }}
  register: out
- debug: var=out.stdout_lines