---
- name: lxd - install needed software
  include_tasks: 01_software.yml

- name: lxd - install config files
  include_tasks: 02_config.yml

- name: lxd - start lxd service
  include_tasks: 03_start.yml

- name: lxd - init with seed
  include_tasks: 04_seed.yml

- name: lxd - create macvlan profile
  include_tasks: 05_macvlan.yml

- name: lxd - import lxd image
  include_tasks: 06_image.yml