---
- name: configure {{ container_name }} ssh authorized_keys - ensure /root/.ssh exists
  shell: |
    /usr/bin/lxc exec {{ container_name }} -- sh -c 'mkdir -p /root/.ssh'
  register: out
- debug: var=out.stdout_lines

- name: configure {{ container_name }} ssh authorized_keys - ensure /root/.ssh with right permissions
  shell: |
    /usr/bin/lxc exec {{ container_name }} -- sh -c 'chmod 0700 /root/.ssh'
  register: out
- debug: var=out.stdout_lines

- name: configure {{ container_name }} ssh authorized_keys - copy authorized_keys into container
  shell: |
    /usr/bin/lxc file push ~/.ssh/authorized_keys "{{ container_name }}"/root/.ssh/authorized_keys
  register: out
- debug: var=out.stdout_lines
