---
- name: repo - ensure gitea is started und enabled
  service:
    name: gitea
    state: started
    enabled: yes
    use: openrc
  register: out
- debug: var=out.stdout_lines

- name: repo - pause for 60 seconds
  pause:
    seconds: 60
  register: out
- debug: var=out.stdout_lines