---
- name: repo - import regen ssh public key
  become: true
  become_user: "{{ gitea_user }}"
  become_method: su
  become_flags: '--login'
  command: >
    /usr/bin/curl -k -H "content-type: application/json"  -H "Authorization: token {{ gitea_repo_user_token }}" 'https://{{ ansible_host }}/api/v1/user/keys' -d '{"title": "regen", "key": "{{ hostvars[groups['regen'][0]].regen_ssh_public_key }}"}'
  register: out
- debug: var=out.stdout_lines