---
- name: repo - ensure needed software installed
  include_tasks: 01_software.yml

- name: repo - create self signed certificate
  include_tasks: 02_certificate.yml

- name: repo - ensure gitea config is created
  include_tasks: 03_config.yml

- name: repo - ensure gitea started
  include_tasks: 04_start.yml

- name: repo - ensure gitea repo user is created
  include_tasks: 05_user.yml

- name: repo - create funtoo repos
  include_tasks: 06_repos.yml

- name: repo - import regen ssh public key
  include_tasks: 07_key.yml