---
- name: repo - ensure needed software installed
  include_tasks: 01_software.yml

- name: repo - create self signed certificate
  include_tasks: 02_certificate.yml

- name: repo - ensure gitea config is created
  include_tasks: 03_config.yml

- name: repo - ensure gitea started
  include_tasks: 04_start.yml

- name: repo - ensure gitea repo user is created
  include_tasks: 05_user.yml

- name: repo - import regen ssh public key
  include_tasks: 06_key.yml

- name: repo - create funtoo orgs
  include_tasks: 07_orgs.yml

- name: repo - create funtoo autogen repos
  include_tasks: 08_repos_auto.yml

- name: repo - create funtoo mirror repos
  include_tasks: 09_repos_mirror.yml
