---
- name: regen - config
  copy:
    src: merge
    dest: "/home/{{ regen_user }}/.merge"
    owner: "{{ regen_user }}"
    group: "{{ regen_user }}"
    mode: 0644
  register: out
- debug: var=out.stdout_lines