---
- name: regen - patches for metatools
  include_tasks: 01_patch.yml

- name: regen - ensure needed software installed
  include_tasks: 02_software.yml

- name: regen - configure tree user
  include_tasks: 03_config.yml

- name: regen - configure regen user
  include_tasks: 04_user.yml